export const FESTIVE_FALL = "Festive Fall";
export const SEQUIN_DJ = "Sequin Denim Jacket";
export const BRATZ_EW = "Bratz Evening Wear";
export const REMNANT = "Remnant Fabric Collection In Process";
export const HADES = "Costume Designer: Hades and Persephone";
export const SLOW = "Slow Fashion In Process";
export const SCIENCE = "Science Fiction Collection";
export const LEAF = "Leaf Block Print";
export const AUTUMN = "Des Automne";